// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3TBE7xzPT7SVUvd04CxLDuc233TCYkQE',
    appId: '1:557847208348:web:a3b37d55c823d5588fe859',
    messagingSenderId: '557847208348',
    projectId: 'midterm-test-67f85',
    authDomain: 'midterm-test-67f85.firebaseapp.com',
    storageBucket: 'midterm-test-67f85.firebasestorage.app',
    measurementId: 'G-2W2414KZLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvjugSuAo-Jl8k_-k4PwtCIinFE6fjag',
    appId: '1:557847208348:android:3bcc8aae9c556b118fe859',
    messagingSenderId: '557847208348',
    projectId: 'midterm-test-67f85',
    storageBucket: 'midterm-test-67f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLVkgc4gPnoeXPsGrIUTPmSVCtpDK_sM',
    appId: '1:557847208348:ios:6a675c9175823ed78fe859',
    messagingSenderId: '557847208348',
    projectId: 'midterm-test-67f85',
    storageBucket: 'midterm-test-67f85.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2351060455',
  );
}
